import { createContext, useContext, ReactNode, useState, useEffect } from 'react';

export type Language = 'pt-BR' | 'en-US' | 'es-ES';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
  formatDate: (date: Date | string, options?: Intl.DateTimeFormatOptions) => string;
  formatDateTime: (date: Date | string, options?: Intl.DateTimeFormatOptions) => string;
  formatNumber: (value: number, options?: Intl.NumberFormatOptions) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Header
    'nav.market': 'Mercado',
    'nav.trending': 'Tendências',
    'nav.converter': 'Conversor',
    'nav.watchlist': 'Watchlist',
    'nav.portfolio': 'Portfólio',
    'nav.login': 'Entrar',
    'nav.register': 'Cadastrar',
    'nav.logout': 'Sair',
    'nav.profile': 'Perfil',
    
    // Home
    'home.title': 'Hoje no Mercado de Criptoativos',
    'home.subtitle': 'Preços por capitalização de mercado',
    'home.live': 'Atualização ao vivo',
    'home.marketCap': 'Capitalização de Mercado',
    'home.volume24h': 'Volume (24h)',
    'home.btcDominance': 'Dominância BTC',
    'home.ethDominance': 'Dominância ETH',
    'home.activeCryptos': 'Criptomoedas Ativas',
    'home.gainers': 'Maiores Altas (24h)',
    'home.losers': 'Maiores Baixas (24h)',
    
    // Table
    'table.rank': '#',
    'table.name': 'Nome',
    'table.price': 'Preço',
    'table.change1h': '1h %',
    'table.change24h': '24h %',
    'table.change7d': '7d %',
    'table.marketCap': 'Market Cap',
    'table.volume': 'Volume (24h)',
    'table.last7d': 'Últimos 7 dias',
    
    // Filters
    'filter.all': 'Todos',
    'filter.gainers': 'Altas',
    'filter.losers': 'Baixas',
    'filter.new': 'Recentes',
    'filter.show': 'Mostrar',
    
    // Auth
    'auth.login': 'Entrar',
    'auth.register': 'Cadastrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.name': 'Nome',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.hasAccount': 'Já tem uma conta?',
    'auth.welcome': 'Bem-vindo de volta!',
    'auth.createAccount': 'Crie sua conta',
    'auth.bonus': 'Ganhe $10.000 de bônus para começar a negociar!',
    'auth.userNotFound': 'Usuário não encontrado',
    'auth.wrongPassword': 'Senha incorreta',
    'auth.emailExists': 'Email já cadastrado',
    'auth.loginSuccess': 'Sessão validada com segurança no backend PHP.',
    'auth.loginError': 'Não foi possível autenticar.',
    'auth.passwordMismatch': 'As senhas não coincidem',
    'auth.accountCreated': 'Conta criada! 🎉',
    'auth.accountCreatedDesc': 'Seu acesso foi configurado no backend PHP e o token JWT foi salvo na sessão atual.',
    'auth.registrationError': 'Não foi possível concluir o cadastro.',
    
    // Portfolio
    'portfolio.title': 'Meu Portfólio',
    'portfolio.balance': 'Saldo Disponível',
    'portfolio.totalValue': 'Valor Total',
    'portfolio.holdings': 'Posições',
    'portfolio.transactions': 'Transações',
    'portfolio.buy': 'Comprar',
    'portfolio.sell': 'Vender',
    'portfolio.amount': 'Quantidade',
    'portfolio.total': 'Total',
    'portfolio.profit': 'Lucro/Prejuízo',
    'portfolio.noHoldings': 'Você ainda não possui nenhuma criptomoeda',
    'portfolio.startTrading': 'Comece a negociar agora',
    'portfolio.buySuccess': 'Compra realizada com sucesso!',
    'portfolio.sellSuccess': 'Venda realizada com sucesso!',
    'portfolio.insufficientBalance': 'Saldo insuficiente',
    'portfolio.insufficientHoldings': 'Você não possui quantidade suficiente',
    
    // Trade
    'trade.buy': 'Comprar',
    'trade.sell': 'Vender',
    'trade.amount': 'Quantidade',
    'trade.price': 'Preço',
    'trade.total': 'Total',
    'trade.fee': 'Taxa (0.1%)',
    'trade.youPay': 'Você paga',
    'trade.youReceive': 'Você recebe',
    'trade.confirm': 'Confirmar',
    'trade.cancel': 'Cancelar',
    'trade.available': 'Disponível',

    // Common
    'common.search': 'Buscar...',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.close': 'Fechar',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.action': 'Ação',
    'common.trade': 'Trade',
    'common.activate': 'Ativar',
    'common.date': 'Data',
    'common.type': 'Tipo',
    'common.asset': 'Ativo',
    'common.quantity': 'Quantidade',
    'common.price': 'Preço',
    'common.total': 'Total',
    'common.fee': 'Taxa',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.theme': 'Tema',
    'settings.language': 'Idioma',
    'settings.currency': 'Moeda',
    'settings.dark': 'Escuro',
    'settings.light': 'Claro',
    'settings.profile': 'Perfil',
    'settings.security': 'Segurança',
    'settings.notifications': 'Notificações',
    'settings.memberSince': 'Membro desde {date}',
    'settings.personalize': 'Personalize sua experiência no CryptoNova',
    'settings.twoFactor': 'Autenticação de 2 Fatores',
    'settings.twoFactorDesc': 'Adicione uma camada extra de segurança',
    'settings.changePassword': 'Alterar Senha',
    'settings.changePasswordDesc': 'Última alteração: há 30 dias',
    'settings.priceAlerts': 'Alertas de Preço',
    'settings.transactionAlerts': 'Alertas de Transação',
    'settings.newsUpdates': 'Novidades e Atualizações',
    'nav.heatmap': 'Heatmap',
    'nav.news': 'Notícias',
    'nav.alerts': 'Alertas',
    'nav.compare': 'Comparar',
    'nav.simulator': 'Simulador',
    'nav.whales': 'Whales',
    'nav.calendar': 'Calendário',
    'nav.tools': 'Ferramentas',
    'nav.principal': 'Principal',
    'nav.moreTools': 'Ferramentas',
    'footer.description': 'A plataforma profissional completa para acompanhar o mercado de criptomoedas.',
    'footer.products': 'Produtos',
    'footer.trading': 'Trading',
    'footer.analytics': 'Análises',
    'footer.legal': 'Legal',
    'footer.liveStatus': 'Mercado ativo • Preços ao vivo',
    'home.promoTitle': 'Comece a negociar com $10.000 de bônus!',
    'home.promoBody': 'Crie sua conta gratuita e receba saldo virtual para comprar e vender criptomoedas. Sem riscos, sem compromisso.',
    'home.ctaFree': 'Cadastrar Grátis',
    'home.liveLabel': 'Atualização ao vivo',
    'home.show': 'Mostrar',
    'home.quickInfo': 'Informações rápidas',
    'home.converterCardTitle': 'Conversor de Moedas',
    'home.converterCardDesc': 'Converta qualquer criptomoeda em moedas fiduciárias instantaneamente.',
    'home.watchlistCardTitle': 'Sua Watchlist',
    'home.watchlistCardDesc': 'Acompanhe suas criptomoedas favoritas em um só lugar.',
    'home.trendingCardTitle': 'Tendências',
    'home.trendingCardDesc': 'Descubra as criptomoedas mais buscadas e em alta no momento.',
    'auth.badge': 'Autenticação real com PHP + MySQL',
    'auth.subtitle': 'Entre ou cadastre-se com um fluxo seguro, validado no backend e protegido por JWT.',
    'auth.featureTradeTitle': 'Trade com Facilidade',
    'auth.featureTradeDesc': 'Compre e venda criptomoedas com taxas baixas (0.1%)',
    'auth.featureDataTitle': 'Dados Persistentes',
    'auth.featureDataDesc': 'Usuário salvo em MySQL com sessão validada pelo backend',
    'auth.featureSecurityTitle': 'Segurança Total',
    'auth.featureSecurityDesc': 'JWT, hash de senha e validação server-side',
    'auth.processing': 'Processando...',
    'auth.namePlaceholder': 'Seu nome',
    'auth.emailPlaceholder': 'seu@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.passwordHint': 'Use pelo menos 8 caracteres, incluindo maiúscula, minúscula, número e símbolo.',
    'auth.realAuth': 'Autenticação real',
    'auth.realAuthDesc': 'JWT, hash seguro de senha e validação no servidor.',
    'trade.backToCoin': 'Voltar para {name}',
    'trade.currentPrice': 'Preço Atual',
    'trade.marketCap': 'Market Cap',
    'trade.volume24h': 'Volume 24h',
    'trade.youOwn': 'Você Possui',
    'trade.quantityLabel': 'Quantidade ({symbol})',
    'trade.max': 'MAX',
    'trade.process': 'Processando...',
    'trade.secureNotice': 'Transação segura via banco de dados criptografado',
    'trade.title': 'Negociar {symbol}',
    'trade.avgPrice': 'Preço Médio',
    'portfolio.greeting': 'Olá, {name}! Aqui está o resumo do seu portfólio.',
    'portfolio.performance': 'Performance do Portfólio',
    'portfolio.distribution': 'Distribuição',
    'portfolio.noAssets': 'Nenhum ativo ainda',
    'portfolio.history': 'Histórico de Transações',
    'portfolio.noTransactions': 'Você ainda não possui transações',
    'portfolio.buildPortfolio': 'Comece a negociar agora e construa seu portfólio',
    'portfolio.exploreMarket': 'Explorar Mercado',
    'portfolio.positions': 'Suas Posições',
    'portfolio.events': 'Eventos do Portfólio',
    'portfolio.trade': 'Negociar',
    'portfolio.invested': 'Valor Investido',
    'portfolio.avgPrice': 'Preço Médio',
    'portfolio.currentPrice': 'Preço Atual',
    'portfolio.value': 'Valor',
    'portfolio.pnl': 'P/L',
    'portfolio.chartPlaceholder': 'Faça sua primeira compra para ver o gráfico',
    'alerts.title': 'Alertas de Preço',
    'alerts.subtitle': 'Seja notificado quando condições específicas forem atendidas',
    'alerts.newAlert': 'Novo Alerta',
    'alerts.activateNotifications': 'Ative as notificações',
    'alerts.enableNotifications': 'Permita notificações no navegador para receber alertas em tempo real',
    'alerts.createAlert': 'Criar Novo Alerta',
    'alerts.create': 'Criar',
    'alerts.active': 'Ativos',
    'alerts.triggered': 'Disparados',
    'alerts.paused': 'Pausados',
    'alerts.loadingAlerts': 'Carregando alertas do banco...',
    'alerts.noneConfigured': 'Nenhum alerta configurado',
    'alerts.createFirst': 'Crie seu primeiro alerta para ser notificado sobre mudanças no mercado',
    'alerts.priceAbove': 'Preço acima de',
    'alerts.priceBelow': 'Preço abaixo de',
    'alerts.changeUp': '↑ Mais que',
    'alerts.changeDown': '↓ Mais que',
    'alerts.activated': 'Notificações ativadas!',
    'alerts.triggeredAt': 'Disparado em {date}',
    'alerts.createdAt': 'Criado em {date}',
    'alerts.activeBadge': 'Ativo',
    'alerts.pausedBadge': 'Pausado',
    'alerts.triggeredBadge': 'Disparado',
    'admin.title': 'Painel Administrativo',
    'admin.subtitle': 'Gerencie usuários, monitore atividades e visualize estatísticas',
    'admin.refresh': 'Atualizar',
    'admin.totalUsers': 'Total de Usuários',
    'admin.activeUsers': 'Ativos',
    'admin.totalTransactions': 'Transações',
    'admin.totalVolume': 'Volume Total',
    'admin.systemStatus': 'Status do Sistema',
    'admin.recentAlerts': 'Alertas Recentes',
    'admin.loadingUsers': 'Carregando do banco...',
    'admin.noUsers': 'Nenhum usuário cadastrado',
    'admin.loadingLogs': 'Carregando logs do banco...',
    'admin.noLogs': 'Nenhum log registrado',
    'admin.user': 'Usuário',
    'admin.email': 'Email',
    'admin.balance': 'Saldo',
    'admin.status': 'Status',
    'admin.lastLogin': 'Último Login',
    'admin.actions': 'Ações',
    'admin.ban': 'Banir',
    'admin.unban': 'Desbanir',
    'admin.online': 'Online',
    'admin.warning': 'Degradado',
    'admin.offline': 'Offline',
    'admin.minutesAgo': '{minutes}min',
    'admin.hoursAgo': '{hours}h',
    'admin.daysAgo': '{days}d',
    'calendar.title': 'Calendário Cripto',
    'calendar.subtitle': 'Próximos eventos importantes do ecossistema cripto',
    'calendar.filterAll': 'Todos',
    'calendar.low': 'Baixo',
    'calendar.medium': 'Médio',
    'calendar.high': 'Alto',
    'calendar.impact': 'Impacto {level}',
    'calendar.soon': 'Em breve',
    'calendar.today': 'Hoje',
    'calendar.inDays': 'em {days} dia{plural}',
    'whales.title': 'Whales e Análise On-Chain',
    'whales.subtitle': 'Monitore grandes movimentações e métricas blockchain em tempo real',
    'whales.moves': '🐋 Movimentações de Whales',
    'whales.onChain': '⛓ Análise On-Chain',
    'whales.activeAddresses': 'Endereços Ativos',
    'whales.transactions24h': 'Transações 24h',
    'whales.totalFees': 'Taxas 24h',
    'whales.hashRate': 'Taxa de Hash',
    'whales.exchangeIn': 'Entrada em Exchange',
    'whales.exchangeOut': 'Saída de Exchange',
    'whales.transfer': 'Transferência',
    'whales.blockTime': 'Tempo de Bloco',
    'whales.difficulty': 'Dificuldade',
    'whales.mempool': 'Mempool',
    'whales.avgGasPrice': 'Taxa Média',
    'whales.networkMetrics': 'Métricas da Rede Bitcoin',
    'whales.topWallets': 'Top Carteiras Ativas',
    'whales.analysisTitle': '📊 Análise On-Chain',
    'whales.analysis1': '• Entradas em exchanges: entradas em exchanges estão baixas, sinalizando acumulação.',
    'whales.analysis2': '• Endereços Ativos: número de endereços ativos cresceu 5.2% nas últimas 24h.',
    'whales.analysis3': '• Acumulação de Whales: carteiras com +1000 BTC aumentaram posições em 2.3% esta semana.',
    'whales.analysis4': '• Atividade da Rede: volume on-chain está 18% acima da média de 30 dias.',
    'simulator.title': 'Simulador de Investimento',
    'simulator.subtitle': 'Projete seus retornos com juros compostos e aportes mensais',
    'simulator.config': 'Configuração',
    'simulator.crypto': 'Criptomoeda',
    'simulator.initialInvestment': 'Investimento Inicial (USD)',
    'simulator.monthlyContribution': 'Aporte Mensal (USD)',
    'simulator.monthlyRate': 'Taxa Mensal de Retorno (%)',
    'simulator.period': 'Período (meses)',
    'simulator.finalBalance': 'Saldo Final',
    'simulator.totalProfit': 'Lucro Total',
    'simulator.roi': 'ROI',
    'simulator.evolution': 'Evolução do Patrimônio',
    'simulator.insights': '💡 Análise',
    'simulator.months': 'meses',
    'simulator.years': 'anos',
    'simulator.balance': 'Saldo',
    'simulator.invested': 'Investido',
    'simulator.insight1': '• Você investirá um total de {amount} ao longo de {months} {period}',
    'simulator.insight2': '• Com retorno médio de {rate}% ao mês, seu patrimônio pode crescer {roi}%',
    'simulator.insight3': '• O equivalente a aproximadamente {coins} {symbol} no preço atual',
    'simulator.warning': '⚠️ Projeção baseada em retornos constantes. Resultados reais podem variar significativamente.',
    'coin.backToMarket': 'Voltar ao mercado',
    'coin.chart': 'Gráfico de Preço ({currency})',
    'coin.area': 'Área',
    'coin.line': 'Linha',
    'coin.candle': 'Candlestick',
    'coin.volumeChart': 'Volume (24h)',
    'coin.stats': 'Estatísticas',
    'coin.fearGreed': 'Fear & Greed',
    'coin.techIndicators': 'Indicadores Técnicos',
    'coin.about': 'Sobre {name}',
    'coin.officialSite': 'Site Oficial',
    'coin.marketCap': 'Capitalização de Mercado',
    'coin.volume24hLabel': 'Volume (24h)',
    'coin.circulatingSupply': 'Oferta Circulante',
    'coin.maxSupply': 'Oferta Máxima',
    'coin.maxSupplyUnlimited': '∞ Ilimitado',
    'coin.allTimeHigh': 'Máxima Histórica',
    'coin.allTimeLow': 'Mínima Histórica',
    'coin.launchYear': 'Ano de Lançamento',
    'coin.change1h': 'Alteração 1h',
    'coin.change24h': 'Alteração 24h',
    'coin.change7d': 'Alteração 7d',
    'coin.related': 'Outras Moedas em Destaque'
  },
  'en-US': {
    // Header
    'nav.market': 'Market',
    'nav.trending': 'Trending',
    'nav.converter': 'Converter',
    'nav.watchlist': 'Watchlist',
    'nav.portfolio': 'Portfolio',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    
    // Home
    'home.title': 'Today\'s Cryptocurrency Market',
    'home.subtitle': 'Prices by market capitalization',
    'home.live': 'Live updates',
    'home.marketCap': 'Market Cap',
    'home.volume24h': 'Volume (24h)',
    'home.btcDominance': 'BTC Dominance',
    'home.ethDominance': 'ETH Dominance',
    'home.activeCryptos': 'Active Cryptocurrencies',
    'home.gainers': 'Top Gainers (24h)',
    'home.losers': 'Top Losers (24h)',
    
    // Table
    'table.rank': '#',
    'table.name': 'Name',
    'table.price': 'Price',
    'table.change1h': '1h %',
    'table.change24h': '24h %',
    'table.change7d': '7d %',
    'table.marketCap': 'Market Cap',
    'table.volume': 'Volume (24h)',
    'table.last7d': 'Last 7 days',
    
    // Filters
    'filter.all': 'All',
    'filter.gainers': 'Gainers',
    'filter.losers': 'Losers',
    'filter.new': 'New',
    'filter.show': 'Show',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.welcome': 'Welcome back!',
    'auth.createAccount': 'Create your account',
    'auth.bonus': 'Get $10,000 bonus to start trading!',
    'auth.userNotFound': 'User not found',
    'auth.wrongPassword': 'Wrong password',
    'auth.emailExists': 'Email already registered',
    'auth.loginSuccess': 'Session validated securely in the PHP backend.',
    'auth.loginError': 'Could not authenticate.',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.accountCreated': 'Account created! 🎉',
    'auth.accountCreatedDesc': 'Your access was configured in the PHP backend and the JWT token was saved in the current session.',
    'auth.registrationError': 'Could not complete registration.',
    
    // Portfolio
    'portfolio.title': 'My Portfolio',
    'portfolio.balance': 'Available Balance',
    'portfolio.totalValue': 'Total Value',
    'portfolio.holdings': 'Holdings',
    'portfolio.transactions': 'Transactions',
    'portfolio.buy': 'Buy',
    'portfolio.sell': 'Sell',
    'portfolio.amount': 'Amount',
    'portfolio.total': 'Total',
    'portfolio.profit': 'Profit/Loss',
    'portfolio.noHoldings': 'You don\'t own any cryptocurrency yet',
    'portfolio.startTrading': 'Start trading now',
    'portfolio.buySuccess': 'Purchase completed successfully!',
    'portfolio.sellSuccess': 'Sale completed successfully!',
    'portfolio.insufficientBalance': 'Insufficient balance',
    'portfolio.insufficientHoldings': 'You don\'t have enough holdings',
    
    // Trade
    'trade.buy': 'Buy',
    'trade.sell': 'Sell',
    'trade.amount': 'Amount',
    'trade.price': 'Price',
    'trade.total': 'Total',
    'trade.fee': 'Fee (0.1%)',
    'trade.youPay': 'You pay',
    'trade.youReceive': 'You receive',
    'trade.confirm': 'Confirm',
    'trade.cancel': 'Cancel',
    'trade.available': 'Available',

    // Common
    'common.search': 'Search...',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.action': 'Action',
    'common.trade': 'Trade',
    'common.activate': 'Activate',
    'common.date': 'Date',
    'common.type': 'Type',
    'common.asset': 'Asset',
    'common.quantity': 'Quantity',
    'common.price': 'Price',
    'common.total': 'Total',
    'common.fee': 'Fee',
    
    // Settings
    'settings.title': 'Settings',
    'settings.theme': 'Theme',
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.dark': 'Dark',
    'settings.light': 'Light',
    'settings.profile': 'Profile',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.memberSince': 'Member since {date}',
    'settings.personalize': 'Personalize your CryptoNova experience',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.twoFactorDesc': 'Add an extra layer of security',
    'settings.changePassword': 'Change Password',
    'settings.changePasswordDesc': 'Last changed: 30 days ago',
    'settings.priceAlerts': 'Price Alerts',
    'settings.transactionAlerts': 'Transaction Alerts',
    'settings.newsUpdates': 'News and Updates',
    'nav.heatmap': 'Heatmap',
    'nav.news': 'News',
    'nav.alerts': 'Alerts',
    'nav.compare': 'Compare',
    'nav.simulator': 'Simulator',
    'nav.whales': 'Whales',
    'nav.calendar': 'Calendar',
    'nav.tools': 'Tools',
    'nav.principal': 'Main',
    'nav.moreTools': 'Tools',
    'footer.description': 'The complete professional platform to follow the cryptocurrency market.',
    'footer.products': 'Products',
    'footer.trading': 'Trading',
    'footer.analytics': 'Analytics',
    'footer.legal': 'Legal',
    'footer.liveStatus': 'Market active • Live prices',
    'home.promoTitle': 'Start trading with $10,000 in bonus!',
    'home.promoBody': 'Create your free account and receive virtual balance to buy and sell cryptocurrencies. No risk, no commitment.',
    'home.ctaFree': 'Sign Up Free',
    'home.liveLabel': 'Live update',
    'home.show': 'Show',
    'home.quickInfo': 'Quick info',
    'home.converterCardTitle': 'Currency Converter',
    'home.converterCardDesc': 'Convert any cryptocurrency into fiat currencies instantly.',
    'home.watchlistCardTitle': 'Your Watchlist',
    'home.watchlistCardDesc': 'Track your favorite cryptocurrencies in one place.',
    'home.trendingCardTitle': 'Trending',
    'home.trendingCardDesc': 'Discover the most searched and rising cryptocurrencies right now.',
    'auth.badge': 'Real authentication with PHP + MySQL',
    'auth.subtitle': 'Sign in or create an account with a secure flow, validated in the backend and protected by JWT.',
    'auth.featureTradeTitle': 'Trade with Ease',
    'auth.featureTradeDesc': 'Buy and sell cryptocurrencies with low fees (0.1%)',
    'auth.featureDataTitle': 'Persistent Data',
    'auth.featureDataDesc': 'User saved in MySQL with session validated by the backend',
    'auth.featureSecurityTitle': 'Full Security',
    'auth.featureSecurityDesc': 'JWT, secure password hash, and server-side validation',
    'auth.processing': 'Processing...',
    'auth.namePlaceholder': 'Your name',
    'auth.emailPlaceholder': 'you@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.passwordHint': 'Use at least 8 characters, including uppercase, lowercase, number, and symbol.',
    'auth.realAuth': 'Real authentication',
    'auth.realAuthDesc': 'JWT, secure password hashing, and server validation.',
    'trade.backToCoin': 'Back to {name}',
    'trade.currentPrice': 'Current Price',
    'trade.marketCap': 'Market Cap',
    'trade.volume24h': 'Volume 24h',
    'trade.youOwn': 'You Own',
    'trade.quantityLabel': 'Amount ({symbol})',
    'trade.max': 'MAX',
    'trade.process': 'Processing...',
    'trade.secureNotice': 'Secure transaction via encrypted database',
    'trade.title': 'Trade {symbol}',
    'trade.avgPrice': 'Average Price',
    'portfolio.greeting': 'Hello, {name}! Here is your portfolio summary.',
    'portfolio.performance': 'Portfolio Performance',
    'portfolio.distribution': 'Distribution',
    'portfolio.noAssets': 'No assets yet',
    'portfolio.history': 'Transaction History',
    'portfolio.noTransactions': 'You do not have any transactions yet',
    'portfolio.buildPortfolio': 'Start trading now and build your portfolio',
    'portfolio.exploreMarket': 'Explore Market',
    'portfolio.positions': 'Your Positions',
    'portfolio.events': 'Portfolio Events',
    'portfolio.trade': 'Trade',
    'portfolio.invested': 'Invested Value',
    'portfolio.avgPrice': 'Average Price',
    'portfolio.currentPrice': 'Current Price',
    'portfolio.value': 'Value',
    'portfolio.pnl': 'P/L',
    'portfolio.chartPlaceholder': 'Make your first purchase to see the chart',
    'alerts.title': 'Price Alerts',
    'alerts.subtitle': 'Get notified when specific conditions are met',
    'alerts.newAlert': 'New Alert',
    'alerts.activateNotifications': 'Enable notifications',
    'alerts.enableNotifications': 'Allow browser notifications to receive real-time alerts',
    'alerts.createAlert': 'Create New Alert',
    'alerts.create': 'Create',
    'alerts.active': 'Active',
    'alerts.triggered': 'Triggered',
    'alerts.paused': 'Paused',
    'alerts.loadingAlerts': 'Loading alerts from the database...',
    'alerts.noneConfigured': 'No alerts configured',
    'alerts.createFirst': 'Create your first alert to be notified about market changes',
    'alerts.priceAbove': 'Price above',
    'alerts.priceBelow': 'Price below',
    'alerts.changeUp': '↑ More than',
    'alerts.changeDown': '↓ More than',
    'alerts.activated': 'Notifications enabled!',
    'alerts.triggeredAt': 'Triggered on {date}',
    'alerts.createdAt': 'Created on {date}',
    'alerts.activeBadge': 'Active',
    'alerts.pausedBadge': 'Paused',
    'alerts.triggeredBadge': 'Triggered',
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'Manage users, monitor activity, and view statistics',
    'admin.refresh': 'Refresh',
    'admin.totalUsers': 'Total Users',
    'admin.activeUsers': 'Active',
    'admin.totalTransactions': 'Transactions',
    'admin.totalVolume': 'Total Volume',
    'admin.systemStatus': 'System Status',
    'admin.recentAlerts': 'Recent Alerts',
    'admin.loadingUsers': 'Loading from database...',
    'admin.noUsers': 'No users registered',
    'admin.loadingLogs': 'Loading logs from database...',
    'admin.noLogs': 'No logs recorded',
    'admin.user': 'User',
    'admin.email': 'Email',
    'admin.balance': 'Balance',
    'admin.status': 'Status',
    'admin.lastLogin': 'Last Login',
    'admin.actions': 'Actions',
    'admin.ban': 'Ban',
    'admin.unban': 'Unban',
    'admin.online': 'Online',
    'admin.warning': 'Degraded',
    'admin.offline': 'Offline',
    'admin.minutesAgo': '{minutes}min',
    'admin.hoursAgo': '{hours}h',
    'admin.daysAgo': '{days}d',
    'calendar.title': 'Crypto Calendar',
    'calendar.subtitle': 'Upcoming events from the crypto ecosystem',
    'calendar.filterAll': 'All',
    'calendar.low': 'Low',
    'calendar.medium': 'Medium',
    'calendar.high': 'High',
    'calendar.impact': 'Impact {level}',
    'calendar.soon': 'Coming soon',
    'calendar.today': 'Today',
    'calendar.inDays': 'in {days} day{plural}',
    'whales.title': 'Whales & On-Chain Analytics',
    'whales.subtitle': 'Track large movements and blockchain metrics in real time',
    'whales.moves': '🐋 Whale Movements',
    'whales.onChain': '⛓ On-Chain Analysis',
    'whales.activeAddresses': 'Active Addresses',
    'whales.transactions24h': 'Transactions 24h',
    'whales.totalFees': 'Fees 24h',
    'whales.hashRate': 'Hash Rate',
    'whales.exchangeIn': 'Exchange Inflows',
    'whales.exchangeOut': 'Exchange Outflows',
    'whales.transfer': 'Transfer',
    'whales.blockTime': 'Block Time',
    'whales.difficulty': 'Difficulty',
    'whales.mempool': 'Mempool',
    'whales.avgGasPrice': 'Average Fee',
    'whales.networkMetrics': 'Bitcoin Network Metrics',
    'whales.topWallets': 'Top Active Wallets',
    'whales.analysisTitle': '📊 On-Chain Analysis',
    'whales.analysis1': '• Exchange Inflows: exchange inflows remain low, signaling accumulation.',
    'whales.analysis2': '• Active Addresses: active addresses rose 5.2% over the last 24h.',
    'whales.analysis3': '• Whale Accumulation: wallets with +1000 BTC increased their positions by 2.3% this week.',
    'whales.analysis4': '• Network Activity: on-chain volume is 18% above the 30-day average.',
    'simulator.title': 'Investment Simulator',
    'simulator.subtitle': 'Project your returns with compound interest and monthly contributions',
    'simulator.config': 'Configuration',
    'simulator.crypto': 'Cryptocurrency',
    'simulator.initialInvestment': 'Initial Investment (USD)',
    'simulator.monthlyContribution': 'Monthly Contribution (USD)',
    'simulator.monthlyRate': 'Monthly Return Rate (%)',
    'simulator.period': 'Period (months)',
    'simulator.finalBalance': 'Final Balance',
    'simulator.totalProfit': 'Total Profit',
    'simulator.roi': 'ROI',
    'simulator.evolution': 'Portfolio Evolution',
    'simulator.insights': '💡 Analysis',
    'simulator.months': 'months',
    'simulator.years': 'years',
    'simulator.balance': 'Balance',
    'simulator.invested': 'Invested',
    'simulator.insight1': '• You will invest a total of {amount} over {months} {period}',
    'simulator.insight2': '• With an average return of {rate}% per month, your portfolio may grow {roi}%',
    'simulator.insight3': '• Equivalent to approximately {coins} {symbol} at the current price',
    'simulator.warning': '⚠️ Projection based on constant returns. Real results may vary significantly.',
    'coin.backToMarket': 'Back to market',
    'coin.chart': 'Price Chart ({currency})',
    'coin.area': 'Area',
    'coin.line': 'Line',
    'coin.candle': 'Candlestick',
    'coin.volumeChart': 'Volume (24h)',
    'coin.stats': 'Statistics',
    'coin.fearGreed': 'Fear & Greed',
    'coin.techIndicators': 'Technical Indicators',
    'coin.about': 'About {name}',
    'coin.officialSite': 'Official Site',
    'coin.marketCap': 'Market Capitalization',
    'coin.volume24hLabel': 'Volume (24h)',
    'coin.circulatingSupply': 'Circulating Supply',
    'coin.maxSupply': 'Max Supply',
    'coin.maxSupplyUnlimited': '∞ Unlimited',
    'coin.allTimeHigh': 'All-Time High',
    'coin.allTimeLow': 'All-Time Low',
    'coin.launchYear': 'Launch Year',
    'coin.change1h': '1h Change',
    'coin.change24h': '24h Change',
    'coin.change7d': '7d Change',
    'coin.related': 'Other Featured Coins'
  },
  'es-ES': {
    // Header
    'nav.market': 'Mercado',
    'nav.trending': 'Tendencias',
    'nav.converter': 'Convertidor',
    'nav.watchlist': 'Lista de Seguimiento',
    'nav.portfolio': 'Portafolio',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',
    'nav.profile': 'Perfil',
    
    // Home
    'home.title': 'Mercado de Criptomonedas de Hoy',
    'home.subtitle': 'Precios por capitalización de mercado',
    'home.live': 'Actualización en vivo',
    'home.marketCap': 'Capitalización de Mercado',
    'home.volume24h': 'Volumen (24h)',
    'home.btcDominance': 'Dominancia BTC',
    'home.ethDominance': 'Dominancia ETH',
    'home.activeCryptos': 'Criptomonedas Activas',
    'home.gainers': 'Mayores Alzas (24h)',
    'home.losers': 'Mayores Bajas (24h)',
    
    // Table
    'table.rank': '#',
    'table.name': 'Nombre',
    'table.price': 'Precio',
    'table.change1h': '1h %',
    'table.change24h': '24h %',
    'table.change7d': '7d %',
    'table.marketCap': 'Cap. Mercado',
    'table.volume': 'Volumen (24h)',
    'table.last7d': 'Últimos 7 días',
    
    // Filters
    'filter.all': 'Todos',
    'filter.gainers': 'Alzas',
    'filter.losers': 'Bajas',
    'filter.new': 'Nuevos',
    'filter.show': 'Mostrar',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.name': 'Nombre',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.welcome': '¡Bienvenido de vuelta!',
    'auth.createAccount': 'Crea tu cuenta',
    'auth.bonus': '¡Obtén $10,000 de bono para comenzar a operar!',
    'auth.userNotFound': 'Usuario no encontrado',
    'auth.wrongPassword': 'Contraseña incorrecta',
    'auth.emailExists': 'Correo ya registrado',
    'auth.loginSuccess': 'Sesión validada con seguridad en el backend PHP.',
    'auth.loginError': 'No se pudo autenticar.',
    'auth.passwordMismatch': 'Las contraseñas no coinciden',
    'auth.accountCreated': '¡Cuenta creada! 🎉',
    'auth.accountCreatedDesc': 'Tu acceso fue configurado en el backend PHP y el token JWT fue guardado en la sesión actual.',
    'auth.registrationError': 'No se pudo completar el registro.',
    
    // Portfolio
    'portfolio.title': 'Mi Portafolio',
    'portfolio.balance': 'Saldo Disponible',
    'portfolio.totalValue': 'Valor Total',
    'portfolio.holdings': 'Posiciones',
    'portfolio.transactions': 'Transacciones',
    'portfolio.buy': 'Comprar',
    'portfolio.sell': 'Vender',
    'portfolio.amount': 'Cantidad',
    'portfolio.total': 'Total',
    'portfolio.profit': 'Ganancia/Pérdida',
    'portfolio.noHoldings': 'Aún no posees ninguna criptomoneda',
    'portfolio.startTrading': 'Comienza a operar ahora',
    'portfolio.buySuccess': '¡Compra realizada con éxito!',
    'portfolio.sellSuccess': '¡Venta realizada con éxito!',
    'portfolio.insufficientBalance': 'Saldo insuficiente',
    'portfolio.insufficientHoldings': 'No tienes suficientes posiciones',
    
    // Trade
    'trade.buy': 'Comprar',
    'trade.sell': 'Vender',
    'trade.amount': 'Cantidad',
    'trade.price': 'Precio',
    'trade.total': 'Total',
    'trade.fee': 'Comisión (0.1%)',
    'trade.youPay': 'Tú pagas',
    'trade.youReceive': 'Tú recibes',
    'trade.confirm': 'Confirmar',
    'trade.cancel': 'Cancelar',
    'trade.available': 'Disponible',

    // Common
    'common.search': 'Buscar...',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.close': 'Cerrar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.action': 'Acción',
    'common.trade': 'Operar',
    'common.activate': 'Activar',
    'common.date': 'Fecha',
    'common.type': 'Tipo',
    'common.asset': 'Activo',
    'common.quantity': 'Cantidad',
    'common.price': 'Precio',
    'common.total': 'Total',
    'common.fee': 'Comisión',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.theme': 'Tema',
    'settings.language': 'Idioma',
    'settings.currency': 'Moneda',
    'settings.dark': 'Oscuro',
    'settings.light': 'Claro',
    'settings.profile': 'Perfil',
    'settings.security': 'Seguridad',
    'settings.notifications': 'Notificaciones',
    'settings.memberSince': 'Miembro desde {date}',
    'settings.personalize': 'Personaliza tu experiencia en CryptoNova',
    'settings.twoFactor': 'Autenticación de 2 Factores',
    'settings.twoFactorDesc': 'Agrega una capa extra de seguridad',
    'settings.changePassword': 'Cambiar Contraseña',
    'settings.changePasswordDesc': 'Último cambio: hace 30 días',
    'settings.priceAlerts': 'Alertas de Precio',
    'settings.transactionAlerts': 'Alertas de Transacción',
    'settings.newsUpdates': 'Novedades y Actualizaciones',
    'nav.heatmap': 'Heatmap',
    'nav.news': 'Noticias',
    'nav.alerts': 'Alertas',
    'nav.compare': 'Comparar',
    'nav.simulator': 'Simulador',
    'nav.whales': 'Whales',
    'nav.calendar': 'Calendario',
    'nav.tools': 'Herramientas',
    'nav.principal': 'Principal',
    'nav.moreTools': 'Herramientas',
    'footer.description': 'La plataforma profesional completa para seguir el mercado de criptomonedas.',
    'footer.products': 'Productos',
    'footer.trading': 'Trading',
    'footer.analytics': 'Análisis',
    'footer.legal': 'Legal',
    'footer.liveStatus': 'Mercado activo • Precios en vivo',
    'home.promoTitle': '¡Comienza a operar con $10,000 de bono!',
    'home.promoBody': 'Crea tu cuenta gratuita y recibe saldo virtual para comprar y vender criptomonedas. Sin riesgos, sin compromiso.',
    'home.ctaFree': 'Registrarse Gratis',
    'home.liveLabel': 'Actualización en vivo',
    'home.show': 'Mostrar',
    'home.quickInfo': 'Información rápida',
    'home.converterCardTitle': 'Convertidor de Moneda',
    'home.converterCardDesc': 'Convierte cualquier criptomoneda en monedas fiduciarias al instante.',
    'home.watchlistCardTitle': 'Tu Watchlist',
    'home.watchlistCardDesc': 'Sigue tus criptomonedas favoritas en un solo lugar.',
    'home.trendingCardTitle': 'Tendencias',
    'home.trendingCardDesc': 'Descubre las criptomonedas más buscadas y en alza en este momento.',
    'auth.badge': 'Autenticación real con PHP + MySQL',
    'auth.subtitle': 'Inicia sesión o crea una cuenta con un flujo seguro, validado en el backend y protegido por JWT.',
    'auth.featureTradeTitle': 'Opera con Facilidad',
    'auth.featureTradeDesc': 'Compra y vende criptomonedas con comisiones bajas (0.1%)',
    'auth.featureDataTitle': 'Datos Persistentes',
    'auth.featureDataDesc': 'Usuario guardado en MySQL con sesión validada por el backend',
    'auth.featureSecurityTitle': 'Seguridad Total',
    'auth.featureSecurityDesc': 'JWT, hash de contraseña y validación en servidor',
    'auth.processing': 'Procesando...',
    'auth.namePlaceholder': 'Tu nombre',
    'auth.emailPlaceholder': 'tu@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.passwordHint': 'Usa al menos 8 caracteres, incluyendo mayúscula, minúscula, número y símbolo.',
    'auth.realAuth': 'Autenticación real',
    'auth.realAuthDesc': 'JWT, hash seguro de contraseña y validación del servidor.',
    'trade.backToCoin': 'Volver a {name}',
    'trade.currentPrice': 'Precio Actual',
    'trade.marketCap': 'Cap. Mercado',
    'trade.volume24h': 'Volumen 24h',
    'trade.youOwn': 'Tú Posees',
    'trade.quantityLabel': 'Cantidad ({symbol})',
    'trade.max': 'MAX',
    'trade.process': 'Procesando...',
    'trade.secureNotice': 'Transacción segura mediante base de datos cifrada',
    'portfolio.greeting': '¡Hola, {name}! Aquí está el resumen de tu portafolio.',
    'portfolio.performance': 'Rendimiento del Portafolio',
    'portfolio.distribution': 'Distribución',
    'portfolio.noAssets': 'Aún no hay activos',
    'portfolio.history': 'Historial de Transacciones',
    'portfolio.noTransactions': 'Aún no tienes transacciones',
    'portfolio.buildPortfolio': 'Comienza a operar ahora y construye tu portafolio',
    'portfolio.exploreMarket': 'Explorar Mercado',
    'portfolio.positions': 'Tus Posiciones',
    'portfolio.events': 'Eventos del Portafolio',
    'portfolio.trade': 'Operar',
    'alerts.title': 'Alertas de Precio',
    'alerts.subtitle': 'Recibe notificaciones cuando se cumplan condiciones específicas',
    'alerts.newAlert': 'Nueva Alerta',
    'alerts.activateNotifications': 'Activa las notificaciones',
    'alerts.enableNotifications': 'Permite notificaciones en el navegador para recibir alertas en tiempo real',
    'alerts.createAlert': 'Crear Nueva Alerta',
    'alerts.create': 'Crear',
    'alerts.active': 'Activos',
    'alerts.triggered': 'Disparados',
    'alerts.paused': 'Pausados',
    'alerts.loadingAlerts': 'Cargando alertas de la base de datos...',
    'alerts.noneConfigured': 'Ninguna alerta configurada',
    'alerts.createFirst': 'Crea tu primera alerta para ser notificado sobre cambios del mercado',
    'alerts.priceAbove': 'Precio por encima de',
    'alerts.priceBelow': 'Precio por debajo de',
    'alerts.changeUp': '↑ Más que',
    'alerts.changeDown': '↓ Más que',
    'alerts.activated': '¡Notificaciones activadas!',
    'alerts.triggeredAt': 'Disparada el {date}',
    'alerts.createdAt': 'Creada el {date}',
    'alerts.activeBadge': 'Activo',
    'alerts.pausedBadge': 'Pausado',
    'alerts.triggeredBadge': 'Disparado',
    'admin.title': 'Panel Administrativo',
    'admin.subtitle': 'Gestiona usuarios, supervisa actividades y visualiza estadísticas',
    'admin.refresh': 'Actualizar',
    'admin.totalUsers': 'Total de Usuarios',
    'admin.activeUsers': 'Activos',
    'admin.totalTransactions': 'Transacciones',
    'admin.totalVolume': 'Volumen Total',
    'admin.systemStatus': 'Estado del Sistema',
    'admin.recentAlerts': 'Alertas Recientes',
    'admin.loadingUsers': 'Cargando de la base de datos...',
    'admin.noUsers': 'Ningún usuario registrado',
    'admin.loadingLogs': 'Cargando logs de la base de datos...',
    'admin.noLogs': 'Ningún log registrado',
    'admin.user': 'Usuario',
    'admin.email': 'Correo',
    'admin.balance': 'Saldo',
    'admin.status': 'Estado',
    'admin.lastLogin': 'Último Acceso',
    'admin.actions': 'Acciones',
    'admin.ban': 'Banear',
    'admin.unban': 'Desbanear',
    'admin.online': 'En línea',
    'admin.warning': 'Degradado',
    'admin.offline': 'Fuera de línea',
    'admin.minutesAgo': '{minutes}min',
    'admin.hoursAgo': '{hours}h',
    'admin.daysAgo': '{days}d',
    'calendar.title': 'Calendario Cripto',
    'calendar.subtitle': 'Próximos eventos del ecosistema cripto',
    'calendar.filterAll': 'Todos',
    'calendar.low': 'Bajo',
    'calendar.medium': 'Medio',
    'calendar.high': 'Alto',
    'calendar.impact': 'Impacto {level}',
    'calendar.soon': 'Pronto',
    'calendar.today': 'Hoy',
    'calendar.inDays': 'en {days} día{plural}',
    'whales.title': 'Whales y Análisis On-Chain',
    'whales.subtitle': 'Monitorea grandes movimientos y métricas blockchain en tiempo real',
    'whales.moves': '🐋 Movimientos de Whales',
    'whales.onChain': '⛓ Análisis On-Chain',
    'whales.activeAddresses': 'Direcciones Activas',
    'whales.transactions24h': 'Transacciones 24h',
    'whales.totalFees': 'Comisiones 24h',
    'whales.hashRate': 'Tasa de Hash',
    'whales.exchangeIn': 'Entradas a Exchange',
    'whales.exchangeOut': 'Salidas de Exchange',
    'whales.transfer': 'Transferencia',
    'whales.blockTime': 'Tiempo de Bloque',
    'whales.difficulty': 'Dificultad',
    'whales.mempool': 'Mempool',
    'whales.avgGasPrice': 'Tarifa Promedio',
    'whales.networkMetrics': 'Métricas de la Red Bitcoin',
    'whales.topWallets': 'Top Carteras Activas',
    'whales.analysisTitle': '📊 Análisis On-Chain',
    'whales.analysis1': '• Entradas a exchanges: las entradas a exchanges siguen bajas, señalizando acumulación.',
    'whales.analysis2': '• Direcciones Activas: las direcciones activas aumentaron 5.2% en las últimas 24h.',
    'whales.analysis3': '• Acumulación de Whales: carteras con +1000 BTC aumentaron sus posiciones 2.3% esta semana.',
    'whales.analysis4': '• Actividad de la Red: el volumen on-chain está 18% por encima del promedio de 30 días.',
    'simulator.title': 'Simulador de Inversión',
    'simulator.subtitle': 'Proyecta tus retornos con interés compuesto y aportes mensuales',
    'simulator.config': 'Configuración',
    'simulator.crypto': 'Criptomoneda',
    'simulator.initialInvestment': 'Inversión Inicial (USD)',
    'simulator.monthlyContribution': 'Aporte Mensual (USD)',
    'simulator.monthlyRate': 'Tasa Mensual de Retorno (%)',
    'simulator.period': 'Periodo (meses)',
    'simulator.finalBalance': 'Saldo Final',
    'simulator.totalProfit': 'Ganancia Total',
    'simulator.roi': 'ROI',
    'simulator.evolution': 'Evolución del Patrimonio',
    'simulator.insights': '💡 Análisis',
    'simulator.months': 'meses',
    'simulator.years': 'años',
    'simulator.balance': 'Saldo',
    'simulator.invested': 'Invertido',
    'simulator.insight1': '• Invertirás un total de {amount} a lo largo de {months} {period}',
    'simulator.insight2': '• Con un retorno promedio de {rate}% al mes, tu patrimonio puede crecer {roi}%',
    'simulator.insight3': '• Equivale aproximadamente a {coins} {symbol} al precio actual',
    'simulator.warning': '⚠️ Proyección basada en retornos constantes. Los resultados reales pueden variar significativamente.',
    'coin.backToMarket': 'Volver al mercado',
    'coin.chart': 'Gráfico de Precio ({currency})',
    'coin.area': 'Área',
    'coin.line': 'Línea',
    'coin.candle': 'Candlestick',
    'coin.volumeChart': 'Volumen (24h)',
    'coin.stats': 'Estadísticas',
    'coin.fearGreed': 'Fear & Greed',
    'coin.techIndicators': 'Indicadores Técnicos',
    'coin.about': 'Sobre {name}',
    'coin.officialSite': 'Sitio Oficial',
    'coin.marketCap': 'Capitalización de Mercado',
    'coin.volume24hLabel': 'Volumen (24h)',
    'coin.circulatingSupply': 'Oferta Circulante',
    'coin.maxSupply': 'Oferta Máxima',
    'coin.maxSupplyUnlimited': '∞ Ilimitado',
    'coin.allTimeHigh': 'Máximo Histórico',
    'coin.allTimeLow': 'Mínimo Histórico',
    'coin.launchYear': 'Año de Lanzamiento',
    'coin.change1h': 'Cambio 1h',
    'coin.change24h': 'Cambio 24h',
    'coin.change7d': 'Cambio 7d',
    'coin.related': 'Otras Monedas Destacadas'
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem('cn_language');
    if (stored && stored in translations) return stored as Language;
    return 'pt-BR';
  });

  useEffect(() => {
    localStorage.setItem('cn_language', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (l: Language) => setLangState(l);

  const t = (key: string, vars?: Record<string, string | number>): string => {
    const template = (translations[lang] as Record<string, string>)[key] || key;
    if (!vars) return template;

    return Object.entries(vars).reduce((acc, [k, v]) => acc.replace(`{${k}}`, String(v)), template);
  };

  const formatDate = (date: Date | string, options?: Intl.DateTimeFormatOptions) => {
    return new Intl.DateTimeFormat(lang, options).format(new Date(date));
  };

  const formatDateTime = (date: Date | string, options?: Intl.DateTimeFormatOptions) => {
    return new Intl.DateTimeFormat(lang, { dateStyle: 'medium', timeStyle: 'short', ...options }).format(new Date(date));
  };

  const formatNumber = (value: number, options?: Intl.NumberFormatOptions) => {
    return new Intl.NumberFormat(lang, options).format(value);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, formatDate, formatDateTime, formatNumber }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
